dist: xenial
arch:
   - amd64
   - ppc64le  
language: python
python: 
   - "2.7"
   - "3.5"
#Installing Requests and Supported Versions
install:
  - python -m pip install requests
script:
  - pytest
